# Generated by Django 2.2.5 on 2019-12-26 19:18

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Memoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produto', models.CharField(max_length=50, verbose_name='Produto')),
            ],
        ),
        migrations.CreateModel(
            name='PlacaDeVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produto', models.CharField(max_length=50, verbose_name='Produto')),
            ],
        ),
        migrations.CreateModel(
            name='PlacaMae',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produto', models.CharField(max_length=50, verbose_name='Produto')),
                ('processadores_suportados', models.CharField(choices=[('INTEL', 'Intel'), ('AMD', 'Amd'), ('ambos', 'Intel e AMD')], max_length=50, verbose_name='Processador Suportado')),
                ('slots', models.IntegerField(choices=[('2', '2'), ('4', '4')], verbose_name='Quantidade de Slots')),
                ('memom_suportada', models.CharField(choices=[('4GB', '4GB'), ('8GB', '8GB'), ('16GB', '16GB'), ('32GB', '32GB'), ('64GB', '64GB')], max_length=10, verbose_name='Memoria suportada')),
                ('video_integrado', models.BooleanField(default=True, verbose_name='Video integrado')),
            ],
        ),
        migrations.CreateModel(
            name='Processador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produto', models.CharField(max_length=50, verbose_name='Produto')),
                ('marca', models.CharField(choices=[('INTEL', 'Intel'), ('AMD', 'Amd'), ('ambos', 'Intel e AMD')], max_length=50, verbose_name='Marca')),
            ],
        ),
        migrations.CreateModel(
            name='MonteSeuPc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtd_de_memoria', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)], verbose_name='Quantidade de Memoria')),
                ('tamanho_da_memoria', models.CharField(choices=[('4GB', '4GB'), ('8GB', '8GB'), ('16GB', '16GB'), ('32GB', '32GB'), ('64GB', '64GB')], max_length=50, verbose_name='Tamanho da Memoria')),
                ('memoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monteseupc.Memoria', verbose_name='Memoria Ram')),
                ('placa_de_video', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='monteseupc.PlacaDeVideo', verbose_name='Placa de Video')),
                ('placa_mae', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monteseupc.PlacaMae', verbose_name='Placa mae')),
                ('processador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monteseupc.Processador', verbose_name='Processador')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': 's',
            },
        ),
    ]
